[package]
name = "counts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "counts"
crate-type = ["cdylib"]

[dependencies]
polars = "0.32.1"
polars-core = "0.32.1"
pyo3 = "0.19.0"
pyo3-polars = "0.6.0"
rayon = "1.7.0"
